INSERT INTO makes VALUES (1, 'Audi');

INSERT INTO makes VALUES (2, 'BMW');

INSERT INTO MODELS VALUES (1, 'A5', 'WAGON', 1);

INSERT INTO USER VALUES(1, 'test@email.com', '$2a$10$sFKmbxbG4ryhwPNx/l3pgOJSt.fW1z6YcUnuE2X8APA/Z3NI/oSpq');

INSERT INTO ROLES VALUES(1, 'admin');

INSERT INTO USER_ROLES VALUES(1, 1);